"""second migration

Revision ID: 192d96f62faa
Revises: 7d20d122703e
Create Date: 2023-12-28 15:53:49.737967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192d96f62faa'
down_revision = '7d20d122703e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
