"""third migration

Revision ID: d5f7a00b63a8
Revises: 192d96f62faa
Create Date: 2023-12-28 15:55:46.511997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f7a00b63a8'
down_revision = '192d96f62faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author_email', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['author_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_ibfk_2', 'blog', type_='foreignkey')
    op.drop_column('blog', 'author_email')
    # ### end Alembic commands ###
